### ISSUE TITLE
Extraction fails on parameters with dash

### ISSUE THREAD

**Issue by XVincentX** [litejs/uri-template-lite#1]
Hey,

The library seems to fail when a templated parameter has a dash inside

`/test/{org-id}`

I've been checking the spec multiple times and I haven't found anything claiming that `-` is an invalid character.

**Comment by lauriro** [comment]
`varspec` is defined in [section 2.3](https://tools.ietf.org/html/rfc6570#section-2.3).

    variable-list =  varspec *( "," varspec )
    varspec       =  varname [ modifier-level4 ]
    varname       =  varchar *( ["."] varchar )
    varchar       =  ALPHA / DIGIT / "_" / pct-encoded

Current RegEx `[\w%.]+` is not strict about spec (as allows dot in beginning/end and does not validate pct-encoding) but matching characters should be correct.

**Comment by XVincentX** [comment]
@lauriro thanks for the prompt reply — I guess I was reading the wrong section then, since I was looking at the `unreserved` chars which were including the `-`; but that is about the literals. Thanks for the clarification.

**Comment by XVincentX** [comment]
@lauriro Is there any way you could point me where I should change this to make it support the `-` character too? Unfortunately OpenAPI 2/3 aren't that strict and such character is valid. I will need to fork this library and let the `-` pass.

**Comment by lauriro** [comment]
Is `-` only char needed? Fast lookup didn't give me OpenAPI spec for path templates

**Comment by XVincentX** [comment]
Yeah unfortunately you won't find the specifics in the spec, since it's pretty vague. My knowledge is coming directly from talking with some committee people in a Slack Channel

**Comment by lauriro** [comment]
I think accepting wider range characters could be in scope of this package.
Could you provide a list of needed characters?

**Comment by XVincentX** [comment]
`-` is the only one I'm aware of that we'd need so far.

**Comment by lauriro** [comment]
Implemented in v20.5.0

**Comment by XVincentX** [comment]
Whoa, that was fast. I'll try it out!

**Comment by XVincentX** [comment]
On a different discussion, I think it's correct that the library would refuse to parse it — I would suggest that such feature (dash-enabled) would be behind a flag set to `false` by default, something like `oasMode`. The decision is up to you though.

**Comment by lauriro** [comment]
> This implementation tries to do a best effort template expansion and leaves erroneous expressions in the returned URI instead of throwing errors.

I think `dash-version` is backwards compatible with `rfc-version`, all officials tests still passes.

**Comment by XVincentX** [comment]
That’s true, it’s just more permissive. I’ll leave the decision up to you. Thanks a lot for this, it let finally me remove a bad workaround I was doing :)
