### ISSUE TITLE
Option for custom decodeURIComponent

### ISSUE THREAD

**Issue by mk-pmb** [litejs/uri-template-lite#5]
> //TODO: decodeURIComponent throws an Error on invalid input, add try-catch

I'd like an option to provide my own decoder function. Would you mind implementing that?

(In case someone's interested, my current candidate is [`decode-uri-component`](https://www.npmjs.com/package/decode-uri-component).)

**Comment by mk-pmb** [comment]
Will this patch be a problem if two modules use this lib and both want to use different decoders?

**Comment by lauriro** [comment]
Yes, it is a hacky way anyway. You could overwrite decoder before every invocation on both libs.

**Comment by mk-pmb** [comment]
How about an optional options object on the constructor, and cache whether a decoder was passed as one of the options?
